[package]
name = "adaptive_hybrid_trie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
congee = {git = "https://github.com/RTEnzyme/art-rs.git"}
fst-rs = {path = "../../FST-rs"}